version: '3.4'
networks:
    mynetworkapi:
services:
    sqlserverdocker:
        container_name: sql-server-docker
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - 1414:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
        networks:
            - mynetworkapi
    bancobase.webapi:
        image: ${DOCKER_REGISTRY-}bancobasewebapi
        build:
          context: . 
          dockerfile: BancoBase.WebAPI/Dockerfile
        networks:
            - mynetworkapi
        depends_on:
            - sqlserverdocker
        ports:
            - 5001:8081

